[package]
name = "prometrics"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]

[dependencies]
atomic_immut = "0.1"
lazy_static = "0.2"
trackable = "0.2"

[target.'cfg(target_os="linux")'.dependencies]
libc = "0.2"
procinfo = "0.4"
